//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DevExpressXpoDemo.Xdb
{

    public partial class Oturumlar : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        string fMachineName;
        public string MachineName
        {
            get { return fMachineName; }
            set { SetPropertyValue<string>(nameof(MachineName), ref fMachineName, value); }
        }
        string fUserName;
        public string UserName
        {
            get { return fUserName; }
            set { SetPropertyValue<string>(nameof(UserName), ref fUserName, value); }
        }
        DateTime fLoginDate;
        public DateTime LoginDate
        {
            get { return fLoginDate; }
            set { SetPropertyValue<DateTime>(nameof(LoginDate), ref fLoginDate, value); }
        }
        string fWinUsername;
        public string WinUsername
        {
            get { return fWinUsername; }
            set { SetPropertyValue<string>(nameof(WinUsername), ref fWinUsername, value); }
        }
        string fIP;
        public string IP
        {
            get { return fIP; }
            set { SetPropertyValue<string>(nameof(IP), ref fIP, value); }
        }
        bool fIsAdmin;
        public bool IsAdmin
        {
            get { return fIsAdmin; }
            set { SetPropertyValue<bool>(nameof(IsAdmin), ref fIsAdmin, value); }
        }
    }

}
